version: "3.9"

services:
  console:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: javascript-v8-engine-console
    volumes: 
      - ".:/app"
    ports:
      - "3001:3000"
    tty: true