apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-01-18T11:16:56Z"
  generation: 1
  labels:
    app: javascript-v8-engine-console
  name: javascript-v8-engine-console
  namespace: default
  resourceVersion: "1506"
  uid: f7b33952-0b92-491b-8a96-ef3254c051af
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: javascript-v8-engine-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javascript-v8-engine-console
    spec:
      containers:
      - image: caprilespe/javascript-v8-engine-console:v2
        imagePullPolicy: IfNotPresent
        name: javascript-v8-engine-console
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-01-18T11:16:56Z"
    lastUpdateTime: "2023-01-18T11:17:01Z"
    message: ReplicaSet "javascript-v8-engine-console-65444d7796" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-01-18T11:17:48Z"
    lastUpdateTime: "2023-01-18T11:17:48Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
